name: Data validation

on:
  pull_request:
    branches: [ main, master, develop, "**" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r validation/requirements.txt

      - name: Validate CSVs against schema and FKs
        run: |
          python validation/validator.py
